spring:
  data:
    mongodb:
      host: 192.168.0.201
      port: 27018
      database: universityDB
      password: root
      username: root
      authentication-database: admin
server:
  port: 8080
